name: Python CI Pipeline
run-name: ${{ github.actor }} is running the Python CI Pipeline 🚀
on: workflow_dispatch
jobs:
  build-push-dockerimage:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/setup-python@v5.1.0
      - name: list the files
        run: ls -lrt 
        
      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/python-image:1.0 .

      - name: Docker Images List
        run: docker images

      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/python-image:1.0
