name: Python CI Pipeline
run-name: ${{ github.actor }} is running the Python CI Pipeline 🚀
on: workflow_dispatch
jobs:
  build-push-dockerimage:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/setup-python@v5.1.0
        
      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: leelarajan
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build
        run: docker build -t leelarajan/nodejs-image:1.0 .

      - name: Docker Images List
        run: docker images

      - name: Docker Push
        run: docker push leelarajan/nodejs-image:1.0
